name: "copy to central repo"
description: "copy to central repo"
inputs:
  CENTRAL_REPO_TOKEN:
    required: true
    description: "the central repo token"
  REPO_OWNER:
    required: true
    description: "the username where we have the cenral repo "
  REPO_NAME:
    required: true
    description: "the name of the repository"  





runs:
  using: "composite"
  steps:
  - name: Copy to Central Repository
    shell: bash
    run: |
      # Clone the central repository
      git clone https://${{ inputs.REPO_OWNER }}:${{ inputs.CENTRAL_REPO_TOKEN }}@github.com/${{ inputs.REPO_OWNER }}/${{ inputs.REPO_NAME }}.git central-repo
      # Copy the content of src/services to central repository clone
      cp -r src/services/* central-repo/src/services/
        
      # Copy resources.yml to central repository clone
      cp src/resources/resources.yml central-repo/src/resources/
          
      # Commit and push the changes to the central repository
      cd central-repo

      # get list of servvices
      names_list=$(ls src/services/ | grep "^.*service$")
      #Put each name in line
      IFS=$'\n' read -d '' -ra names <<< "$names_list"
      
      # Insert predefined name into the YAML structure
      yaml_content=""
      for name in "${names[@]}"; do
        entry="     $name:\n       path: /src/services/$name\n"
        yaml_content="$yaml_content$entry"
      done

      echo $yaml_content
      # Load the template YAML
      template=$(cat src/serverless-compose-template.yml)

      # Replace the {name} placeholder with the predefined words
      final_yaml=$(echo "$template" | sed "s@{names}@$yaml_content@")

      # Write the final YAML data to a file
      echo -e "$final_yaml" > src/serverless-compose.yml

      echo "YAML file generated successfully."

      mv src/serverless-compose.yml serverless-compose.yml

      git config user.email "actions@github.com"
      git config user.name "GitHub Actions"
      git add -A .
      git commit -m "Automatic copy of valid files"

      # Set Git remote to the central repository
      git remote set-url origin https://${{ inputs.REPO_OWNER }}:${{ inputs.CENTRAL_REPO_TOKEN }}@github.com/${{ inputs.REPO_OWNER }}/${{ inputs.REPO_NAME}}.git
          

      git push origin main
    env:
      CENTRAL_REPO_TOKEN: ${{ inputs.CENTRAL_REPO_TOKEN }}
